#pragma config(Sensor, S1,     giro,           sensorEV3_Gyro)
#pragma config(Sensor, S4,     ultra,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          derecha,       tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          izquierda,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true){

		int dist = getUSDistance(S4);

		if (dist > 10){
			setMotorSpeed(motorB, -40);
			setMotorSpeed(motorD, -40);


		}

		else{
			setMotorSpeed(motorB, 0);
			setMotorSpeed(motorD, 0);
			sleep(100);
			resetGyro(S1);
			repeatUntil(getGyroDegrees(S1) > 85)
			{
				//Point turn to the left   MIENTRAS ESTA A MENOS DE 85ª
				setMotorSpeed(motorD, 50);
				setMotorSpeed(motorB, -50);

			}

			setMotorSpeed(motorD, 0);
			setMotorSpeed(motorB, 0);
			sleep(100);
			resetGyro(S1);
			backward(1.7, rotations, 40);




//////////////////////////////////////////////////////////////////////////////////////////


	    repeatUntil(getGyroDegrees(S1) > 85)
			{
				//Point turn to the left   MIENTRAS ESTA A MENOS DE 85ª
				setMotorSpeed(motorD, 50);
				setMotorSpeed(motorB, -50);

			}}

			if (dist > 10){
				setMotorSpeed(motorB, -40);
				setMotorSpeed(motorD, -40);


		}

		else{


					resetGyro(S1);
					repeatUntil(getGyroDegrees(S1) > 85)
					{
						//Point turn to the left   MIENTRAS ESTA A MENOS DE 85ª
						setMotorSpeed(motorD, -50);
						setMotorSpeed(motorB, 50);

					}

					setMotorSpeed(motorD, 0);
					setMotorSpeed(motorB, 0);
					sleep(100);
					resetGyro(S1);
					backward(1.7, rotations, 40);


		}




































	/*	//This program will reset the gyro's heading and
	//then turn the robot 90 degrees from its current position

	//Resets the gyro on port 2 to 0 degrees
	resetGyro(S1);

	//Keep looping until the gyro sensor reads greater
	//than 90 degrees from its current position
	repeatUntil(getGyroDegrees(S1) > 90)
	{
	//Point turn to the left
	setMotorSpeed(motorD, -50);
	setMotorSpeed(motorB, 50);
	}

	//Stop the motors at the end of the turn
	setMotorSpeed(motorD, 0);
	setMotorSpeed(motorC, 0);



	*/
	}//loop
	}//main
